title: "SCRIBE: Machine transcription of Norwegian conversational speech"
description: "Project SCRIBE Public Website"
google_analytics:
show_downloads: false
theme: minima

gems:
  - jekyll-mentions
  - minima
